import { beforeAll,afterAll,it,expect,vi } from 'vitest';
import { readFile,readdir } from 'node:fs/promises';
import { Pool } from 'pg';
import { randomUUID } from 'node:crypto';
import { capture,sessionView } from '../../src/lib/sessions';
import { processSession } from '../../src/lib/conversation';
import { pool } from '../../src/lib/db';
import type { Actor,Facts } from '../../src/lib/domain';
import { ProviderError } from '../../src/lib/errors';
const mocks=vi.hoisted(()=>({extract:vi.fn(),queryBusy:vi.fn()}));
vi.mock('../../src/lib/providers',()=>({getLanguageProvider:()=>({extract:mocks.extract}),getCalendarProvider:async()=>({queryBusy:mocks.queryBusy})}));
const url=process.env.TEST_DATABASE_URL!;
const admin=new Pool({connectionString:url});
const actor:Actor={id:randomUUID(),workspaceId:randomUUID(),email:'test@local.test',displayName:'Test'};
const facts:Facts={intent:'appointment',title:'Inspection',date:'2035-01-01',time:'10:00',durationMinutes:30,location:'Warehouse',locationNotApplicable:false,timeZone:'Asia/Dubai',ambiguities:[]};
beforeAll(async()=>{
 if(!url||!new URL(url).pathname.endsWith('_test'))throw new Error('Isolated test database required');
 process.env.DATABASE_URL=url;process.env.APP_MODE='demo';
 await admin.query('DROP SCHEMA IF EXISTS private CASCADE;DROP SCHEMA public CASCADE;CREATE SCHEMA public;');
 await admin.query(await readFile('db/bootstrap-local.sql','utf8'));
 for(const file of (await readdir('db/migrations')).filter(f=>f.endsWith('.sql')).sort())await admin.query(await readFile('db/migrations/'+file,'utf8'));
 await admin.query("INSERT INTO va_workspaces(id,name) VALUES($1,'Test')",[actor.workspaceId]);
 await admin.query('INSERT INTO va_workers(id,workspace_id,email,display_name) VALUES($1,$2,$3,$4)',[actor.id,actor.workspaceId,actor.email,actor.displayName]);
 await admin.query("INSERT INTO private.va_calendar_connections(workspace_id,calendar_id,calendar_label,provider) VALUES($1,'test','Test','simulated')",[actor.workspaceId]);
});
afterAll(async()=>{await admin.end();await pool().end();});
it('anchors extraction to persisted input time and preserves extracted facts when calendar is unavailable',async()=>{
 const saved=await capture(actor,{text:'Book inspection tomorrow',source:'typed',clientCaptureId:randomUUID()});
 const anchor='2026-10-07T19:59:00.000Z';
 await admin.query("UPDATE va_turns SET created_at=$2 WHERE session_id=$1 AND speaker='user'",[saved.id,anchor]);
 mocks.extract.mockResolvedValue({facts,usage:{requestId:randomUUID(),inputTokens:null,outputTokens:null}});
 mocks.queryBusy.mockRejectedValue(new ProviderError('CALENDAR_UNAVAILABLE'));
 await processSession(actor,saved.id);
 const failure=(await admin.query("SELECT detail FROM private.va_operation_events WHERE subject_id=$1 AND event_type='conversation.processing_failed'",[saved.id])).rows[0];
 expect(failure.detail.errorCode).toBe('CALENDAR_UNAVAILABLE');expect(failure.detail.processingMsBeforeCommit).toBeGreaterThanOrEqual(0);
 expect(mocks.extract.mock.calls[0][2]).toBe(anchor);
 const failed=await sessionView(actor,saved.id);expect(failed.state).toBe('failed');expect(failed.facts).toEqual(facts);
 mocks.queryBusy.mockResolvedValue([]);
 await processSession(actor,saved.id,false);
 const recovered=await sessionView(actor,saved.id);expect(recovered.state).toBe('ready');expect(recovered.proposal?.snapshot.title).toBe('Inspection');
});
