'use client';
import {useEffect,useRef,useState} from 'react';
import {RefreshCw,ShieldCheck} from 'lucide-react';
type User={id:string;userCode:string;displayName:string;limit:number;used:number;active:number;remaining:number;exhausted:boolean;permissions?:Record<string,boolean>};
async function request(path:string,body?:unknown){const response=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error?.message??'Unable to load user controls.');return data;}
export function Headquarters(){
 const [users,setUsers]=useState<User[]>([]),[error,setError]=useState(''),[pending,setPending]=useState<string|null>(null),[loaded,setLoaded]=useState(false);
 const loading=useRef(false),alive=useRef(true);
 const load=async()=>{if(loading.current)return;loading.current=true;try{const data=await request('/api/hq');if(alive.current){setUsers(data.users);setLoaded(true);setError('');}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Unable to load user controls.');}finally{loading.current=false;}};
 useEffect(()=>{alive.current=true;void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},3000);const focus=()=>{if(document.visibilityState==='visible')void load();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return()=>{alive.current=false;clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);};},[]);
 const reset=async(user:User)=>{if(pending)return;setPending(user.userCode);setError('');try{await request('/api/hq',{userCode:user.userCode});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to reset requests.');}finally{setPending(null);}};
 const permission=async(user:User,name:string,value:boolean)=>{if(pending)return;setPending(user.userCode);try{await request('/api/settings',{action:'permissions',userCode:user.userCode,permissions:{...user.permissions,[name]:value}});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update access.');}finally{setPending(null);}};
 return <><div className="page-heading heading-row"><div><p className="eyebrow">ADMIN CONTROLS</p><h1>HQ</h1><p>User access and request usage.</p></div><button className="secondary" aria-label="Refresh user controls" onClick={()=>void load()}><RefreshCw size={17}/></button></div>{error&&<div className="error-box" role="alert">{error}</div>}<div className="hq-live" role="status"><span className="demo-dot"/>Updates every 3 seconds · Admins have unlimited requests</div><section className="hq-users" aria-label="User controls">{!loaded&&!error&&<p role="status">Loading users…</p>}{users.map(user=><article className="details-card hq-user" key={user.id}><div className="hq-user-heading"><div><h2>{user.userCode}</h2><small>{user.displayName}</small></div><span className={`status ${user.exhausted?'warning':''}`}>{user.exhausted?'Limit reached':`${user.remaining} remaining`}</span></div><div className="hq-counts"><div><strong>{user.used} / {user.limit}</strong><small>Completed actions</small></div><div><strong>{user.active}</strong><small>In progress</small></div></div><button className="secondary full-width" aria-label={`Reset requests for ${user.userCode}`} disabled={pending!==null} onClick={()=>void reset(user)}><RefreshCw size={16}/>Reset to 3 requests</button>{user.permissions&&<details className="compact-details"><summary><ShieldCheck size={15}/>User permissions</summary><div className="hq-permissions">{['capture','tasks','calendar','audit','settings'].map(name=><label className="checkbox-label" key={name}><input type="checkbox" checked={user.permissions?.[name]!==false} disabled={pending!==null} onChange={e=>void permission(user,name,e.target.checked)}/>{name==='audit'?'Audit logs':name[0].toUpperCase()+name.slice(1)}</label>)}</div></details>}</article>)}</section></>;
}
