'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, AudioLines, CalendarDays, Check, CheckCircle2, Clock3, FileText, LayoutDashboard, Loader2, LogOut, MapPin, MessageSquare, Plus, RefreshCw, ShieldCheck, Sparkles, X } from 'lucide-react';
import type { Actor, DashboardItem, Facts, SessionView } from '@/lib/domain';
import { SectionHub } from './SectionHub';
import { AgentConversation } from './AgentConversation';

type Mode='demo'|'live';
type Filter='all'|'event'|'note'|'request';
type View='capture'|'dashboard'|'session'|'tasks'|'calendar'|'audit'|'settings';
const labels:Record<string,string>={captured:'Captured',clarifying:'Needs details',ready:'Ready to confirm',confirming:'Booking in progress',booked:'Booked',note_saved:'Note saved',booking_unknown:'Needs verification',failed:'Needs attention',unknown:'Needs verification',succeeded:'Booked',reserved:'Booking in progress',writing:'Booking in progress'};
const dateTime=(value:string,zone='Asia/Dubai')=>new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(new Date(value));
async function api<T>(path:string,body?:unknown):Promise<T>{
  const response=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});
  const data=await response.json(); if(!response.ok) throw new Error(data.error?.message??'Something went wrong. Please try again.'); return data;
}
function Status({state}:{state:string}){return <span className={`status ${['booked','succeeded','note_saved'].includes(state)?'success':['booking_unknown','unknown','failed'].includes(state)?'warning':''}`}><span/>{labels[state]??state.replaceAll('_',' ')}</span>;}

export function Workspace({initialMode}:{initialMode:Mode}){
 const [mode,setMode]=useState(initialMode),[speechAvailable,setSpeechAvailable]=useState(initialMode==='live'),[worker,setWorker]=useState<Actor|null>(null),[boot,setBoot]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [view,setView]=useState<View>('capture'),[text,setText]=useState(''),[reply,setReply]=useState(''),[session,setSession]=useState<SessionView|null>(null),[items,setItems]=useState<DashboardItem[]>([]),[cursor,setCursor]=useState<string|null>(null),[filter,setFilter]=useState<Filter>('all'),[editing,setEditing]=useState(false),[recording,setRecording]=useState(false),[now,setNow]=useState(Date.now());
 const [loginRole,setLoginRole]=useState<'user'|'admin'>('user'),[userCode,setUserCode]=useState('user1'),[alias,setAlias]=useState(''),[adminCode,setAdminCode]=useState('');
 const keys=useRef(new Map<string,string>());
 const running=useRef(false);
 const pendingCapture=useRef<{text:string;source:'typed'|'browser_voice'}|null>(null);
 const key=(operation:string,payload:unknown)=>{const fingerprint=operation+JSON.stringify(payload);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());return keys.current.get(fingerprint)!;};
 useEffect(()=>{api<{worker:Actor;mode:Mode}>('/api/me').then(v=>{setWorker(v.worker);setMode(v.mode);}).catch(()=>{}).finally(()=>setBoot(false));},[]);
 useEffect(()=>{api<{speechAvailable:boolean}>('/api/config').then(v=>setSpeechAvailable(v.speechAvailable)).catch(()=>{});},[]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const run=async(fn:()=>Promise<void>)=>{if(running.current)return;running.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{running.current=false;setBusy(false);}};
 const dashboard=async(nextFilter:Filter=filter,after?:string)=>{const result=await api<{items:DashboardItem[];nextCursor:string|null}>(`/api/dashboard?type=${nextFilter}${after?`&cursor=${encodeURIComponent(after)}`:''}`);setItems(previous=>after?[...previous,...result.items]:result.items);setCursor(result.nextCursor);};
 const login=(body:unknown)=>run(async()=>{await api('/api/auth/login',body);const me=await api<{worker:Actor;mode:Mode}>('/api/me');setWorker(me.worker);setMode(me.mode);keys.current.clear();});
 const open=(id:string)=>run(async()=>{const result=await api<{session:SessionView}>(`/api/sessions/${id}`);setSession(result.session);setEditing(false);setReply('');setView('session');});
 const accept=(result:{session:SessionView})=>{setSession(result.session);setView('session');setEditing(false);};
 const capture=(input=text,source:'typed'|'browser_voice'='typed')=>run(async()=>{const payload=pendingCapture.current?.text===input.trim()?pendingCapture.current:{text:input.trim(),source};pendingCapture.current=payload;accept(await api('/api/captures',{...payload,clientCaptureId:key('capture',payload)}));pendingCapture.current=null;setText('');keys.current.clear();});
 const turn=(input=reply)=>run(async()=>{if(!session)return;const payload={text:input.trim(),expectedVersion:session.version};accept(await api(`/api/sessions/${session.id}/turns`,{...payload,clientTurnId:key('turn:'+session.id,payload)}));setReply('');});
 const note=()=>run(async()=>{if(!session)return;const payload={expectedVersion:session.version};accept(await api(`/api/sessions/${session.id}/note`,{...payload,clientActionId:key('note:'+session.id,payload)}));});
 const confirm=()=>run(async()=>{if(!session?.proposal)return;const p=session.proposal,payload={proposalVersion:p.version,snapshotHash:p.snapshotHash};accept(await api(`/api/proposals/${p.id}/confirm`,{...payload,idempotencyKey:key('confirm:'+p.id,payload)}));});
 const saveFacts=(facts:Partial<Facts>)=>run(async()=>{if(!session)return;const payload={facts,expectedVersion:session.version};accept(await api(`/api/sessions/${session.id}/edit`,{...payload,clientActionId:key('edit:'+session.id,payload)}));});
 const agentView=view==='capture'||view==='session';
 const locked=!!session&&(session.contentExpired||['confirming','booked','note_saved','booking_unknown'].includes(session.state));
 const newCapture=()=>{pendingCapture.current=null;setView('capture');setSession(null);setText('');setReply('');setError('');setEditing(false);};
 if(boot)return <main className="boot" role="status"><Loader2 className="spin" size={34}/><p>Opening your workspace…</p></main>;
 if(!worker)return <main className="login-page"><section className="login-story"><div className="brand"><span className="brand-mark"><AudioLines/></span>Nova<span className="brand-light"> Agent</span></div><div><p className="eyebrow">LESS ADMIN. MORE HUMAN.</p><h1>Say it.<br/>Shape it.<br/><span>Make time for it.</span></h1><p className="story-copy">Turn everyday requests into clear notes and confirmed appointments. You always make the final call.</p></div><span className="story-footer"><ShieldCheck size={18}/> Your workspace. Your decisions.</span></section><section className="login-card"><span className="small-icon"><Sparkles size={24}/></span><p className="eyebrow">YOUR WORKSPACE</p><h2>Welcome back</h2><p className="muted">Capture the details. We’ll help with the rest.</p><form onSubmit={e=>{e.preventDefault();void login({userCode:loginRole==='admin'?'admin':userCode,name:alias,code:loginRole==='admin'?adminCode:undefined});}}><div className="tabs login-role"><button type="button" className={loginRole==='user'?'selected':''} onClick={()=>setLoginRole('user')}>User</button><button type="button" className={loginRole==='admin'?'selected':''} onClick={()=>setLoginRole('admin')}>Admin</button></div>{loginRole==='user'&&<label htmlFor="login-user-code">User code<select id="login-user-code" value={userCode} onChange={e=>setUserCode(e.target.value)}><option value="user1">user1</option><option value="user2">user2</option></select></label>}<label htmlFor="login-alias">Your name<input id="login-alias" value={alias} onChange={e=>setAlias(e.target.value)} required maxLength={80} autoComplete="nickname"/></label>{loginRole==='admin'&&<label htmlFor="login-admin-code">Admin code<input id="login-admin-code" value={adminCode} onChange={e=>setAdminCode(e.target.value)} required inputMode="numeric" type="password" autoComplete="off"/></label>}<button className="primary" disabled={busy||!alias.trim()}>Open workspace<ArrowRight size={18}/></button></form>{error&&<div role="alert" className="error-box">{error}</div>}<p className="login-foot">Pilot access · Your name is a temporary alias. User codes identify activity.</p></section></main>;
 return <div className={`app-shell ${agentView?'agent-shell':''}`}><aside className="sidebar"><div className="brand"><span className="brand-mark"><AudioLines/></span>Nova<span className="brand-light"> Agent</span></div><div className="workspace-label">NOVA WORKSPACE<span>PILOT</span></div><nav aria-label="Main navigation"><button className={view==='capture'||view==='session'?'nav-item active':'nav-item'} onClick={newCapture} disabled={busy}><Plus size={19}/>Talk to agent</button><button className={view==='dashboard'?'nav-item active':'nav-item'} disabled={busy} onClick={()=>{setView('dashboard');void run(()=>dashboard());}}><LayoutDashboard size={19}/>My activity</button>{(['tasks','calendar','audit','settings'] as const).map(section=><button key={section} className={view===section?'nav-item active':'nav-item'} disabled={busy} onClick={()=>{setView(section);setError('');}}>{section==='calendar'?<CalendarDays size={19}/>:section==='audit'?<ShieldCheck size={19}/>:section==='tasks'?<CheckCircle2 size={19}/>:<Sparkles size={19}/>}<span>{section==='audit'?'Audit logs':section[0].toUpperCase()+section.slice(1)}</span></button>)}</nav><div className="sidebar-bottom"><div className="quiet-card"><ShieldCheck size={21}/><strong>You’re in control</strong><p>Appointments are created only after you confirm the details.</p></div><div className="profile"><span className="avatar">{worker.displayName.slice(0,1)}</span><div><strong>{worker.displayName}</strong><small>{(worker as Actor & {userCode?:string;role?:string}).userCode??'user'} · {(worker as Actor & {role?:string}).role??'user'}</small></div><button aria-label="Sign out" className="icon-button" disabled={busy} onClick={()=>run(async()=>{await api('/api/auth/logout',{});setWorker(null);setSession(null);setItems([]);setText('');setReply('');setView('capture');keys.current.clear();})}><LogOut size={17}/></button></div></div></aside>
 <main className="main">{agentView&&<div className="agent-toolbar"><span className="brand"><span className="brand-mark"><AudioLines/></span>Nova Agent</span><div><button className="secondary" disabled={busy||recording} onClick={()=>{setView('tasks');setError('');}}><LayoutDashboard size={17}/>Dashboard</button><button aria-label="Sign out" className="icon-button" disabled={busy||recording} onClick={()=>run(async()=>{await api('/api/auth/logout',{});setWorker(null);setSession(null);setItems([]);setText('');setReply('');setView('capture');keys.current.clear();})}><LogOut size={20}/></button></div></div>}{agentView&&<div className="agent-user"><span className="agent-user-name">{worker.userCode??'user'} · {worker.displayName}</span><span>UAE · GMT+4</span></div>}<header className="topbar"><span className="breadcrumb">Workspace <span>/</span> <strong>{view==='dashboard'?'My activity':view==='session'?'Conversation':view==='capture'?'New capture':view==='audit'?'Audit logs':view[0].toUpperCase()+view.slice(1)}</strong></span><span className="timezone"><Clock3 size={14}/>UAE · GMT+4</span></header><div className="mobile-nav"><select aria-label="Dashboard section" value={view==='session'?'capture':view} onChange={e=>{const next=e.target.value as View;setView(next);if(next==='dashboard')void run(()=>dashboard());}}><option value="capture">Capture</option><option value="dashboard">Activity</option><option value="tasks">Tasks</option><option value="calendar">Calendar</option><option value="audit">Audit logs</option><option value="settings">Settings</option></select><button onClick={newCapture} disabled={busy}><Plus size={17}/>Capture</button><button disabled={busy} onClick={()=>{setView('dashboard');void run(()=>dashboard());}}><LayoutDashboard size={17}/>Activity</button><button disabled={busy} aria-label="Sign out" onClick={()=>run(async()=>{await api('/api/auth/logout',{});setWorker(null);setSession(null);setItems([]);setText('');setReply('');setView('capture');keys.current.clear();})}><LogOut size={17}/></button></div>
 {mode==='demo'&&<div className="demo-banner"><span className="demo-dot"/><strong>Local demo</strong><span>Pilot workspace · Built-in calendar · Voice requires provider access</span></div>}
 <div className="content">{error&&<div className="error-box" role="alert"><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
 {(['tasks','calendar','audit','settings'] as string[]).includes(view)&&<SectionHub key={view} section={view as 'tasks'|'calendar'|'audit'|'settings'} worker={worker}/>}
 {view==='dashboard'&&<><div className="page-heading heading-row"><div><p className="eyebrow">EVERYTHING IN ONE PLACE</p><h1>My activity</h1><p>Your notes, requests and confirmed appointments.</p></div><button className="primary" onClick={newCapture} disabled={busy}><Plus size={18}/>New capture</button></div><div className="activity-summary"><span><LayoutDashboard size={20}/><strong>{items.length}</strong> loaded records</span><span><CalendarDays size={20}/> Calendar & notes <span className="muted">· Private to you</span></span></div><div className="activity-card"><div className="activity-toolbar"><div className="tabs" aria-label="Activity filter">{(['all','event','note','request'] as const).map(value=><button aria-pressed={filter===value} className={filter===value?'selected':''} disabled={busy} key={value} onClick={()=>{setFilter(value);void run(()=>dashboard(value));}}>{value==='all'?'All activity':value==='event'?'Appointments':value==='note'?'Notes':'Requests'}</button>)}</div><button className="icon-button" aria-label="Refresh activity" disabled={busy} onClick={()=>run(()=>dashboard())}><RefreshCw size={17} className={busy?'spin':''}/></button></div>{items.length===0?<div className="empty-state"><FileText size={32}/><h2>A clear space to start</h2><p>Your captures will appear here. Start with a note or an appointment.</p><button className="secondary" onClick={newCapture}>Create your first capture<ArrowRight size={17}/></button></div>:<div className="activity-list">{items.map(item=><button key={item.id} disabled={busy} className="activity-item" onClick={()=>open(item.sessionId)}><span className={`record-icon ${item.kind}`}>{item.kind==='event'?<CalendarDays size={20}/>:item.kind==='note'?<FileText size={20}/>:<MessageSquare size={20}/>}</span><span className="record-copy"><strong>{item.contentExpired?'Content expired':item.title}</strong><small>{item.startsAt?dateTime(item.startsAt)+' · UAE':dateTime(item.createdAt)}</small></span><Status state={item.status}/><ArrowRight size={17}/></button>)}</div>}{cursor&&<div className="load-more"><button className="secondary" disabled={busy} onClick={()=>run(()=>dashboard(filter,cursor))}>Load more</button></div>}</div></>}
 {(agentView)&&<AgentConversation session={session} busy={busy} locked={locked} speechAvailable={speechAvailable} value={session?reply:text} onChange={session?setReply:setText} onSend={(value,source)=>session?void turn(value):void capture(value,source)} onRecordingChange={setRecording} onNew={newCapture}>
 {session&&<div className="agent-review"><div className="agent-review-heading"><Status state={session.state}/><button className="icon-button" aria-label="Refresh conversation" disabled={busy||recording} onClick={()=>open(session.id)}><RefreshCw size={16}/></button></div><aside className="details-column">
 {['captured','failed'].includes(session.state)&&<div className="uncertain-card"><RefreshCw size={23}/><h2>Continue this request</h2><p>Your text is saved. Resume to process it without creating another capture.</p><button className="secondary" disabled={busy||recording} onClick={()=>run(async()=>accept(await api(`/api/sessions/${session.id}/resume`,{})))}>Resume request<ArrowRight size={16}/></button></div>}{session.state==='booked'&&<div className="outcome-card"><CheckCircle2 size={30}/><h2>Appointment confirmed</h2><p>{mode==='demo'?'Saved in the workspace calendar.':'Your appointment has been added to the calendar.'}</p></div>}
 {session.state==='note_saved'&&<div className="outcome-card"><CheckCircle2 size={30}/><h2>Note saved</h2><p>You can find it anytime in My activity.</p></div>}
 {['booking_unknown','confirming'].includes(session.state)&&<div className="uncertain-card"><Clock3 size={25}/><h2>{session.state==='booking_unknown'?'Booking status uncertain':'Checking your booking'}</h2><p>Do not create another booking for this request. Check the existing attempt to avoid a duplicate.</p><button className="secondary" disabled={busy||recording||!session.attempt} onClick={()=>run(async()=>{if(session.attempt)accept(await api(`/api/attempts/${session.attempt.id}/resume`,{}));})}><RefreshCw size={16}/>Check booking status</button></div>}
 {session.proposal&&session.state==='ready'&&<section className="confirmation-card"><span className="eyebrow"><Check size={15}/> READY FOR YOUR REVIEW</span><h2>{session.proposal.snapshot.title}</h2><p><CalendarDays size={17}/>{dateTime(session.proposal.snapshot.start,session.proposal.snapshot.timeZone)}</p><p><Clock3 size={17}/>Ends {dateTime(session.proposal.snapshot.end,session.proposal.snapshot.timeZone)}</p><p><MapPin size={17}/>{session.proposal.snapshot.location??'Not applicable'}</p><small>{session.proposal.snapshot.timeZone} · Shared calendar</small><div className="confirm-divider"/><p className="confirm-note">{Date.parse(session.proposal.expiresAt)<=now?'This confirmation has expired. Edit the details to check availability again.':`Availability will be checked again. Confirm within ${Math.max(1,Math.ceil((Date.parse(session.proposal.expiresAt)-now)/60000))} min.`}</p><button className="primary full-width" disabled={busy||recording||Date.parse(session.proposal.expiresAt)<=now} onClick={confirm}>{busy?<Loader2 className="spin" size={17}/>:<Check size={17}/>}Confirm appointment</button></section>}
 {editing?<FactsEditor facts={session.facts} busy={busy||recording} onCancel={()=>setEditing(false)} onSave={saveFacts}/>:<section className="details-card"><div className="section-title"><CalendarDays size={18}/><h2>Request details</h2>{!locked&&<button className="text-button" disabled={busy||recording} onClick={()=>setEditing(true)}>Edit</button>}</div><dl><dt>Title</dt><dd>{session.facts.title??'Not set yet'}</dd><dt>Date & time</dt><dd>{session.facts.date??'Date needed'}{session.facts.time?' · '+session.facts.time:''}<small>{session.facts.timeZone}</small></dd><dt>Duration</dt><dd>{session.facts.durationMinutes?`${session.facts.durationMinutes} minutes`:'Duration needed'}</dd><dt>Location</dt><dd>{session.facts.locationNotApplicable?'Not applicable':session.facts.location??'Location needed'}</dd></dl>{!locked&&<button className="secondary full-width" disabled={busy||recording} onClick={note}><FileText size={16}/>Save as note</button>}</section>}
 </aside></div>}
 </AgentConversation>}
 </div><footer className="app-footer"><span>NOVA AGENT · PILOT</span><span>Thoughtfully captured. Personally confirmed.</span></footer></main></div>;
}

function FactsEditor({facts,busy,onSave,onCancel}:{facts:Facts;busy:boolean;onSave:(facts:Partial<Facts>)=>void;onCancel:()=>void}){
 const [draft,setDraft]=useState(facts);
 const submit=(e:FormEvent)=>{e.preventDefault();onSave(draft);};
 return <form className="details-card facts-editor" onSubmit={submit}><div className="section-title"><h2>Edit details</h2><button type="button" className="icon-button" onClick={onCancel} aria-label="Cancel edit"><X size={18}/></button></div><label>Title<input value={draft.title??''} onChange={e=>setDraft({...draft,title:e.target.value||null})} maxLength={200}/></label><label>Date<input type="date" value={draft.date??''} onChange={e=>setDraft({...draft,date:e.target.value||null})}/></label><label>Start time · UAE<input type="time" value={draft.time??''} onChange={e=>setDraft({...draft,time:e.target.value||null})}/></label><label>Duration in minutes<input type="number" min={1} max={1440} value={draft.durationMinutes??''} onChange={e=>setDraft({...draft,durationMinutes:e.target.value?Number(e.target.value):null})}/></label><label>Location<input disabled={draft.locationNotApplicable} value={draft.location??''} onChange={e=>setDraft({...draft,location:e.target.value||null})}/></label><label className="checkbox-label"><input type="checkbox" checked={draft.locationNotApplicable} onChange={e=>setDraft({...draft,locationNotApplicable:e.target.checked,location:e.target.checked?null:draft.location})}/>Location not applicable</label><button className="primary full-width" disabled={busy}>Save details<Check size={17}/></button></form>;
}
